# Product:
# C Include Include File Files Auto Generator
# CIIFFAG 1.0.0
#
# 2023.08.23
# MatiMati

import glob
import os

input_file_path = "./Source/**/*.h"
output_directory_path = "./Include/"

raw_header_path_list = glob.glob(input_file_path, recursive=True)
header_file_name_list = [os.path.basename(header_path) for header_path in raw_header_path_list]

header_path_list = [header_path.replace("\\","/").replace("./", "../") for header_path in raw_header_path_list]

# Generate include files by header
for (header_path, header_file_name) in zip(header_path_list, header_file_name_list):
    try:
        with open(output_directory_path + header_file_name, mode='x') as header_file:
            header_file.write("/* This file generated by CIIFFAG 1.0 */\n")
            header_file.write("#include \"" + header_path + "\"\n")
    except FileExistsError:
        continue